### Variables 
@apiurl = http://localhost:8080/api

### GET tasks
GET {{apiurl}}/tasks HTTP/1.1

### POST tasks - create
POST {{apiurl}}/tasks HTTP/1.1
Content-Type: application/json

{
   "title": "Run in the morning"
}

### GET - task by id
GET {{apiurl}}/tasks/cd123cf7-0f47-4235-9925-dbc839efedf7 HTTP/1.1

### REMOVE - task by id
DELETE {{apiurl}}/tasks/cd123cf7-0f47-4235-9925-dbc839efedf7 HTTP/1.1

### UPDATE - task by id
PATCH {{apiurl}}/tasks/fcdbbad4-05b8-453c-99e3-5619f363d804
Content-Type: application/json

{
   "title": "Do the dishes"
}
